[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Xss-Protection = "0"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "interest-cohort=(), browsing-topics=(), camera=(), microphone=(), geolocation=(), usb=()"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Resource-Policy = "cross-origin"
    Access-Control-Allow-Origin = "*"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Origin-Agent-Cluster = "?1"
    Server = "Jarema"
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me gateway.umami.is cloud.umami.is; font-src 'self'; img-src 'self'; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live; style-src 'self' 'unsafe-inline'; base-uri 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me ws.audioscrobbler.com gateway.umami.is cloud.umami.is status.cafe; font-src 'self'; frame-src jarema.atabook.org; img-src 'self' *.ytimg.com *.rcd.gg *.googleusercontent.com moods.imood.com lastfm.freetls.fastly.net; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/??/"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me ws.audioscrobbler.com gateway.umami.is cloud.umami.is status.cafe; font-src 'self'; frame-src jarema.atabook.org; img-src 'self' *.ytimg.com *.rcd.gg *.googleusercontent.com moods.imood.com lastfm.freetls.fastly.net; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/blog/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me gateway.umami.is cloud.umami.is; font-src 'self'; img-src 'self' https:; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live; style-src 'self' 'unsafe-inline'; base-uri 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/??/blog/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me gateway.umami.is cloud.umami.is; font-src 'self'; img-src 'self' https:; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live; style-src 'self' 'unsafe-inline'; base-uri 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/about/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me api.maptiler.com gateway.umami.is cloud.umami.is; font-src 'self'; frame-src api.maptiler.com; img-src 'self' api.maptiler.com tiles.openstreetmap.org; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live; style-src 'self' 'unsafe-inline'; base-uri 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/??/about/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me api.maptiler.com gateway.umami.is cloud.umami.is; font-src 'self'; frame-src api.maptiler.com; img-src 'self' api.maptiler.com tiles.openstreetmap.org; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live; style-src 'self' 'unsafe-inline'; base-uri 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/now/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me ws.audioscrobbler.com gateway.umami.is cloud.umami.is status.cafe; font-src 'self'; img-src 'self' *.ytimg.com *.rcd.gg *.googleusercontent.com moods.imood.com lastfm.freetls.fastly.net; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live; style-src 'self' 'unsafe-inline'; base-uri 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/??/now/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me ws.audioscrobbler.com gateway.umami.is cloud.umami.is status.cafe; font-src 'self'; img-src 'self' *.ytimg.com *.rcd.gg *.googleusercontent.com moods.imood.com lastfm.freetls.fastly.net; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live; style-src 'self' 'unsafe-inline'; base-uri 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/guestbook/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me gateway.umami.is cloud.umami.is; font-src 'self'; frame-src jarema.atabook.org; img-src 'self' https:; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/??/guestbook/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me gateway.umami.is cloud.umami.is; font-src 'self'; frame-src jarema.atabook.org; img-src 'self' https:; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/records/*"
  [headers.values]
    Request-OTR = "1"
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    CDN-Cache-Control = "no-store"
    Pragma = "no-cache"
    Expires = "0"
    Cross-Origin-Resource-Policy = "same-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me gateway.umami.is cloud.umami.is; font-src 'self'; img-src 'self'; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; base-uri 'self'; frame-ancestors 'self'; upgrade-insecure-requests"

[[headers]]
  for = "/??/records/*"
  [headers.values]
    Request-OTR = "1"
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    CDN-Cache-Control = "no-store"
    Pragma = "no-cache"
    Expires = "0"
    Cross-Origin-Resource-Policy = "same-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me gateway.umami.is cloud.umami.is; font-src 'self'; img-src 'self'; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; base-uri 'self'; frame-ancestors 'self'; upgrade-insecure-requests"

[[headers]]
  for = "/retro/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me gateway.umami.is cloud.umami.is; font-src 'self'; img-src 'self' moods.imood.com lastfm.freetls.fastly.net; manifest-src 'self'; media-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/chat/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me gateway.umami.is cloud.umami.is iframe.chat; font-src 'self'; frame-src iframe.chat; img-src 'self' https:; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live iframe.chat; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[headers]]
  for = "/??/chat/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' jarema.me gateway.umami.is cloud.umami.is iframe.chat; font-src 'self'; frame-src iframe.chat; img-src 'self' https:; manifest-src 'self'; media-src 'self'; script-src 'self' 'unsafe-inline' vercel.live iframe.chat; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self'; frame-ancestors 'self' https: geekring.net kagi.com; upgrade-insecure-requests"

[[redirects]]
  from = "/tools/counter/*"
  to = "/tools/text-counter/:splat"
  status = 301

[[redirects]]
  from = "/:locale/tools/counter/*"
  to = "/:locale/tools/text-counter/:splat"
  status = 301

[[redirects]]
  from = "/stats/*"
  to = "https://cloud.umami.is/:splat"
  status = 200
